version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: github_mysql1
    environment:
      MYSQL_DATABASE: dam
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: github_keycloak1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassxyz
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_FEATURES: "scripts"
    ports:
      - "8081:8080"
    command: >
      start-dev --health-enabled=true --features=scripts --spi-script-upload-enabled=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3