spring.security.oauth2.client.provider.keycloak.issuer-uri=https://${HOST_DOMAIN:localhost}:8081/realms/${KEYCLOAK_REALM_NAME:DAM}
keycloak.auth-server-url=https://${HOST_DOMAIN:localhost}:8081
HOST_DOMAIN_URI=https://${HOST_DOMAIN:localhost}
deployment.wipe-data=${WIPE_DATA:false}
deployment.seed-data=${SEED_DATA:true}