spring.application.name=DAM
spring.datasource.url=jdbc:mysql://localhost:3306/dam
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

## Keycloak
spring.security.oauth2.client.registration.keycloak.client-id=backend-client
spring.security.oauth2.client.registration.keycloak.client-secret=uXGN4bmUo1kUdKGWNWSZJGePE8CxKczj
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/DAM