spring.application.name=DAM
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/dam}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:W!n9#Dam!Q#2025_}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
server.port=${SERVER_PORT:8080}
server.address=${SERVER_ADDRESS:0.0.0.0}

## Keycloak
spring.security.oauth2.client.registration.keycloak.client-id=backend-client
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:uXGN4bmUo1kUdKGWNWSZJGePE8CxKczj}
spring.security.oauth2.client.registration.keycloak.scope=openid
keycloak.realm=DAM


## Google
google.oauth2.issuer-uri=https://accounts.google.com
google.oauth2.jwks-uri=https://www.googleapis.com/oauth2/v3/certs

auth.provider=${AUTH_PROVIDER:keycloak}

## Log4j
logging.level.root=INFO
logging.level.com.verlake.dam=DEBUG
logging.file.name=logs/dev-application.log
logging.config=classpath:logback-spring.xml