spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/DAM
keycloak.auth-server-url=http://localhost:8081
HOST_DOMAIN_URI=http://localhost:5173

# Disable DevTools restart - fixes TokenService.class not found (classloader issue on restart)
spring.devtools.restart.enabled=false