input {
  tcp {
    port => 12324  # This should match the port in your Spring Boot application (LogstashTcpSocketAppender)
    host => "0.0.0.0"
    codec => json_lines
  }
}

filter {
  # You can add filters here to process logs, for example, adding timestamps, parsing JSON, etc.
  # Example: parse log messages in JSON format if not already in the correct format
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_URL}:9243"]
    index => "dam-hagrids-logstash-%{+YYYY.MM.dd}"
    user => "elastic"   # Your Elasticsearch username
    password => "${ELASTIC_PASSWORD}"  # Your Elasticsearch password
    ssl => true  # Enable SSL if you're using HTTPS
  }
}