name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Check out the code from the repository
    - uses: actions/checkout@v4

    # Set up Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Set up Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    # Run Gradle build
    - name: Build with Gradle Wrapper
      run: ./gradlew build --stacktrace

    # Run Tests and Capture Results
    - name: Run Tests
      run: ./gradlew test --stacktrace

    # Publish Test Results
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/test

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Check out the code from the repository
    - uses: actions/checkout@v4

    # Set up Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generate and submit dependency graph for Dependabot
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4.0.0
