name: Nightly Build with AWS SES Notification

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: "0 0 * * *"  # Change if you want a different schedule
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual trigger of the workflow

env:
  GOOGLE_ISSUE_URI: https://accounts.google.com
  GOOGLE_JWKS_URI: https://www.googleapis.com/oauth2/v3/certs
  KEYCLOAK_URL: http://localhost:8081
  HOST_DOMAIN_URI: http://localhost
  MAIL_SENDER: test@dam.com
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  backend_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # To fetch repository content
    services:
      docker:
        image: docker:24.0
    outputs:
      timestamp: ${{ steps.timestamp_output.outputs.timestamp }}
    steps:
      # Checkout repository code
      - uses: actions/checkout@v4

      - name: Load .env variables
        run: |
          # Load the .env file
          set -o allexport
          source .env
          set +o allexport
          # Save the variables to GITHUB_ENV
          echo "AUTH_PROVIDER=$AUTH_PROVIDER" >> $GITHUB_ENV
          echo "HOST_REGION=$HOST_REGION" >> $GITHUB_ENV
          echo "KEYCLOAK_REALM_NAME=$KEYCLOAK_REALM_NAME" >> $GITHUB_ENV
          echo "KEYCLOAK_ADMIN_USERNAME=$KEYCLOAK_ADMIN_USERNAME" >> $GITHUB_ENV
          echo "MYSQL_URL=$MYSQL_URL" >> $GITHUB_ENV
          echo "MYSQL_USERNAME=$MYSQL_USERNAME" >> $GITHUB_ENV
          echo "HOST_IP_ADDRESS=$HOST_IP_ADDRESS" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> $GITHUB_ENV
          echo "BACKEND_ARTIFACT_PREFIX=$BACKEND_ARTIFACT_PREFIX" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "KEYCLOAK_ADMIN_USER_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_USER_PASSWORD }}" >> $GITHUB_ENV
          echo "KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Set timestamp variable
        id: timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      # Set timestamp as output for the next job
      - name: Set timestamp as output for next job
        id: timestamp_output
        run: echo "timestamp=${{ env.timestamp }}" >> "$GITHUB_OUTPUT"

      # Install Docker Compose and set up MySQL/Keycloak
      - name: Install Docker Compose and AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose python3 python3-pip
          sudo pip3 install awscli --upgrade --user

      - name: Set up Docker Compose
        run: |
          docker-compose --env-file .env -f .github/docker-compose.yml up -d

      - name: Wait for MySQL and Keycloak to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          timeout 120s bash -c 'while ! mysqladmin ping -h127.0.0.1 --silent; do sleep 5; done'
        shell: bash

      - name: Wait for Keycloak to be ready
        run: |
          echo "Waiting for Keycloak to be ready..."
          timeout 120s bash -c 'until curl -s -o /dev/null -w "%{http_code}" ${{ env.KEYCLOAK_URL }}/realms/master | grep -q "200"; do
            echo "Waiting for Keycloak to be ready..."; sleep 5;
          done'

      # Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # Import Keycloak Realm Configuration
      - name: Setup Keycloak Realm
        run: |
          echo "Fetching admin token..."
          TOKEN=$(curl -s -X POST ${{ env.KEYCLOAK_URL }}/realms/master/protocol/openid-connect/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=${{ env.KEYCLOAK_ADMIN_USERNAME }}" \
            -d "password=${{ env.KEYCLOAK_ADMIN_USER_PASSWORD }}" \
            -d "grant_type=password" \
            -d "client_id=admin-cli" | jq -r '.access_token')

          # Verify if token is retrieved
          if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
            echo "Failed to retrieve Keycloak admin token!"
            exit 1
          fi

          echo "Successfully retrieved Keycloak admin token."

          # Create Keycloak realm
          echo "Setting up Keycloak realm..."
          curl -s -X POST ${{ env.KEYCLOAK_URL }}/admin/realms \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            --data-binary "@src/main/resources/keycloak/realm-export.json"

          echo "Keycloak realm setup completed!"
      # Build backend project with Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle Wrapper
        run: ./gradlew build --stacktrace -Dspring-boot.run.profiles=dev

      # Bundle the build artifact (JAR) into a zip file
      - name: Bundle backend build artifact
        run: |
          ls -la
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "MYSQL_PASSWORD=\"${{ secrets.MYSQL_PASSWORD }}\"" >> .env
          echo "KEYCLOAK_ADMIN_USER_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_USER_PASSWORD }}" >> .env
          echo "KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}" >> .env
          echo "MAIL_SENDER=${{ secrets.MAIL_SENDER }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "APM_SECRET_TOKEN=\"${{ secrets.APM_SECRET_TOKEN }}\"" >> .env
          cp .env build/libs/
          cd build/libs/
          ls -la
          zip -r "../../${{ env.BACKEND_ARTIFACT_PREFIX }}-${{ env.timestamp }}.zip" ./* .env
          cd ../..


      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.HOST_REGION }}
      # Upload to AWS S3 using AWS Access and Secret keys
      - name: Upload backend artifact to S3
        run: |
          aws s3 cp "${{ env.BACKEND_ARTIFACT_PREFIX }}-${{ env.timestamp }}.zip" s3://${{ env.S3_BUCKET_NAME }}/ \
            --region ${{ env.HOST_REGION }}

  notify_on_failure:
    needs: backend_build
    if: failure()  # Only runs if any of the previous jobs fail
    runs-on: ubuntu-latest

    steps:

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          sudo pip3 install awscli --upgrade --user
      - name: Load .env variables
        run: |
          # Load the .env file
          set -o allexport
          source .env
          set +o allexport
          # Save the variables to GITHUB_ENV
          echo "HOST_REGION=$HOST_REGION" >> $GITHUB_ENV

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.HOST_REGION }}

      - name: Send failure notification email using AWS SES
        run: |
          SUBJECT="Nightly Build Failure"
          BODY="The nightly build for the backend has failed. Please check the logs for more details."
          EMAIL_FROM="m_abhi@mindslake.com"  # Verified email address in SES
          EMAIL_TO="abhinandanb@mindslake.com"  # Email to notify in case of failure

          aws ses send-email \
            --region ${{ env.HOST_REGION }} \
            --from "$EMAIL_FROM" \
            --destination "ToAddresses=$EMAIL_TO" \
            --message "Subject={Data=$SUBJECT},Body={Text={Data=$BODY}}"

  deploy_to_ec2:
    needs: backend_build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variable
        run: |
          echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Load .env variables
        run: |
          # Load the .env file
          set -o allexport
          source .env
          set +o allexport
          # Save the variables to GITHUB_ENV
          echo "HOST_DOMAIN=$HOST_DOMAIN" >> $GITHUB_ENV
          echo "HOST_IP_ADDRESS=$HOST_IP_ADDRESS" >> $GITHUB_ENV
          echo "HOST_USER=$HOST_USER" >> $GITHUB_ENV
          echo "HOST_REGION=$HOST_REGION" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> $GITHUB_ENV
          echo "BACKEND_ARTIFACT_PREFIX=$BACKEND_ARTIFACT_PREFIX" >> $GITHUB_ENV
          echo "MYSQL_URL=$MYSQL_URL" >> $GITHUB_ENV
          echo "MYSQL_USERNAME=$MYSQL_USERNAME" >> $GITHUB_ENV
          echo "MYSQL_DB_NAME=$MYSQL_DB_NAME" >> $GITHUB_ENV
          echo "KEYCLOAK_ADMIN_USERNAME=$KEYCLOAK_ADMIN_USERNAME" >> $GITHUB_ENV
          echo "KEYCLOAK_REALM_NAME=$KEYCLOAK_REALM_NAME" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "KEYCLOAK_ADMIN_USER_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_USER_PASSWORD }}" >> $GITHUB_ENV
          echo "KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ELASTICSEARCH_URL=$ELASTICSEARCH_URL" >> $GITHUB_ENV
          echo "ELASTIC_PASSWORD=${{ secrets.APM_AUTH_PASSWORD }}" >> $GITHUB_ENV

      - name: Update and install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Set up SSH for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.HOST_IP_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Generate inventory.ini from template
        run: |
          export HOST_IP_ADDRESS=${{ env.HOST_IP_ADDRESS }}
          export HOST_USER=${{ env.HOST_USER }}
          envsubst < ansible/inventory.ini.j2 > ansible/inventory.ini
          cat ansible/inventory.ini
          
      - name: Generate logstash.conf from template
        run: |
          export ELASTICSEARCH_URL=${{ env.ELASTICSEARCH_URL }}
          export ELASTIC_PASSWORD=${{ env.ELASTIC_PASSWORD }}
          envsubst < ./src/main/resources/logstash/logstash_temp.conf > logstash.conf
          cat logstash.conf

      - name: Upload realm-export.json and logstash.conf to EC2
        run: |
          scp -i ~/.ssh/id_rsa ./src/main/resources/keycloak/realm-export.json ${{ env.HOST_USER }}@${{ env.HOST_IP_ADDRESS }}:/tmp/realm-export.json
          scp -i ~/.ssh/id_rsa logstash.conf ${{ env.HOST_USER }}@${{ env.HOST_IP_ADDRESS }}:/tmp/logstash.conf

      - name: Deploy to EC2 using Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/mysql_install.yml -e "db_name=${{ env.MYSQL_DB_NAME }} db_password=${{ env.MYSQL_PASSWORD }}"
          ansible-playbook -i ansible/inventory.ini ansible/keycloak_install.yml -e "host_domain=${{ env.HOST_DOMAIN }} ec2_ip=${{ env.HOST_IP_ADDRESS }} s3_bucket=${{ env.S3_BUCKET_NAME }} keycloak_admin_user=${{ env.KEYCLOAK_ADMIN_USERNAME }} keycloak_admin_password=${{ env.KEYCLOAK_ADMIN_USER_PASSWORD }} keycloak_client_secret=${{ env.KEYCLOAK_CLIENT_SECRET }} realm_name=${{ env.KEYCLOAK_REALM_NAME }}"
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml -e "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }} aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} host_ip_address=${{ env.HOST_IP_ADDRESS }} domain_name=${{ env.HOST_DOMAIN }} s3_bucket=${{ env.S3_BUCKET_NAME }} host_user=${{ env.HOST_USER }} backend_artifact=${{ env.BACKEND_ARTIFACT_PREFIX }}-${{ needs.backend_build.outputs.timestamp }}.zip"
          ansible-playbook -i ansible/inventory.ini ansible/logstash_install.yml -e host_user=${{ env.HOST_USER }}
